dynamic_resources:
  lds_config:
    path: "/Users/dchiesa/dev/envoy/dino-configs/lds.yaml"
  cds_config:
    path: "/Users/dchiesa/dev/envoy/dino-configs/cds.yaml"
node:
  id: "id_01"
  cluster: "cluster_01"
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
